spring:
  application:
    name: '@project.artifactId@'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/perf_db
    username: root
    password: root123

server:
  port: 8080