spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api
logging:
  level:
    org.springframework.data.rest.webmvc.json.ProjectionProjector: DEBUG
