auth:
  adminUser: admin
  adminPassword: adminpassword

service:
  type: ClusterIP #ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: keycloak.localhost     # <— au lieu de hosts[0].host
  path: /
  pathType: Prefix
  tls: false                       # mets true + secret si tu veux du HTTPS

extraEnvVars:
  - name: KC_HOSTNAME              # recommandé sur Keycloak Quarkus récent
    value: keycloak.localhost
  - name: KC_HOSTNAME_STRICT
    value: "true"

postgresql:
  enabled: true
  image:
    tag: "14"   # ou une 14.x précise (ex: 14.12.0-debian-12-rXX)
  auth:
    postgresPassword: pgrootpassword
    username: bn_keycloak
    password: keycloakpass
    database: bitnami_keycloak
