server:
  port: 8181

spring:
  application:
    name: "product-protobuf-consumer"

  kafka:
    bootstrap-servers: localhost:9093
    security:
      protocol: "SSL"  # Assurez-vous que le serveur Kafka est configuré pour utiliser SSL
    ssl:
      endpoint.identification.algorithm: ""
      key-store-location: classpath:client_certs/client-consumer.keystore.jks  # Vérifiez le chemin
      key-store-password: password  # Assurez-vous que c'est le bon mot de passe
      trust-store-location: classpath:client_certs/client-consumer.truststore.jks  # Vérifiez le chemin
      trust-store-password: password  # Assurez-vous que c'est le bon mot de passe
    consumer:
      ssl:
        endpoint.identification.algorithm: ""
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest   # Consommer les messages depuis le début si l'offset n'est pas trouvé
      enable-auto-commit: false     # Désactivation de l'acquittement automatique

      # Configuration si on est batch processing
      # Nombre maximum de messages à lire en une seule interrogation (par défaut 500)
      max-poll-records: 500        # Par défaut, 500 messages peuvent être récupérés à chaque fois
      # Valeurs spécifiques aux performances
      fetch-max-wait: 500 # Temps maximal que Kafka attendra avant d'envoyer les messages au consommateur (par défaut : 500 ms)
      fetch-min-size: 1   # Nombre minimum d'octets pour envoyer un lot de messages au consommateur (par défaut : 1 octet)
      # End Configuration si on est batch processing

    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        protobuf:
          value:
            type: com.esprit.proto.product.Product
    listener:
      missing-topics-fatal: false
      ack-mode: manual # Mode manuel pour l'acquittement des messages