server:
  servlet:
    context-path: '/@project.artifactId@'
  #port: 8081


spring:
  application:
    name: '@project.artifactId@'

  cloud:
    stream:
      bindings:
        produceMessage-out-0:
          destination: demo-topic
        consumeMessage-in-0:
          destination: demo-topic
      kafka:
        binder:
          brokers: ${BROKER_HOST_AND_PORT}
    function:
      definition: consumeMessage; #produceMessage