server:
  port: 8081
spring:
  application:
    name: "principal"
  #profiles:
  #  active: "local"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    properties:
      hibernate:
      #generate_statistics: true
      #format_sql: true
      #use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: root
    password: root123

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    contexts: local


#library:
#  liquibase:
#    changelog-path: classpath:/db/changelog/db.changelog-master.yml