port: 8080
spring:
  application:
    name: "library"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:file:./data/library-db
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #liquibase:
  #  enabled: true
  #  change-log: classpath:/db/changelog/db.changelog-master.yml


library:
  liquibase:
    changelog-path: classpath:/db/changelog/db.changelog-master.yml
